### PR TITLE
Update Fulcio certificate issuance doc

### PR DESCRIPTION
**Pull request by haydentherapper**
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Comment by haydentherapper** [comment]
@ltagliaferri - I updated the Fulcio docs to match what's in public documentation. How do I update the images? Is there a public tool for this? I need to update 5 (it's not loading), 6, and 8, and add a 7th image, based on https://github.com/sigstore/fulcio/pull/702/files

**Comment by haydentherapper** [comment]
@vaikas Do you happen to know how images were created for the documentation?

**Comment by vaikas** [comment]
I think that was actually Nathan who did some drawings earlier and I thought Excalidraw is what he used.

**Comment by haydentherapper** [comment]
These diagrams appear to be different. I was able to update the images for the Fulcio docs in the fulcio repo previously. I might switch over to Excalidraw images for these docs, I am a big fan.

**Review by ltagliaferri — APPROVED** [review]

**Pull request merged**
