### PR TITLE
Add more critical project dates

### PR DESCRIPTION
**Pull request by haydentherapper**

### CODE REVIEW

**Comment by haydentherapper** [comment]
@ltagliaferri , do you know if this is correct to edit this? I saw a mention of manually editing it here - https://www.sigstore.dev/admin/#/collections/story/entries/storyDates - but I guessed that was out of date?

**Comment by haydentherapper** [comment]
From what I can tell, I think those contribution guidelines are out of date, I think updating this json here is sufficient

**Review by trevrosen — APPROVED** [review]
Thanks for this @haydentherapper - you're a game day player for real 🎉

**Review by bobcallaway — APPROVED** [review]

**Review by ltagliaferri — APPROVED** [review]

**Comment by haydentherapper** [comment]
https://www.sigstore.dev/community - looks nice!

**Pull request merged**
