### PR TITLE
Use ```shell for copyable install code blocks

### PR DESCRIPTION
**Pull request by imjasonh**
Signed-off-by: Jason Hall <jasonhall@redhat.com>

### CODE REVIEW

**Comment by imjasonh** [comment]
It doesn't seem to copy without the `$` 😢 

https://deploy-preview-110--sigstore.netlify.app/cosign/installation

**Review by dlorenc — COMMENTED** [review]
So actually (and we're not consistent about this), but I heard somewhere that ```console is better than ```shell because then the $ character isn't copied. Does that work here?

**Comment by imjasonh** [comment]
> So actually (and we're not consistent about this), but I heard somewhere that `console is better than `shell because then the $ character isn't copied. Does that work here?

Nope 😢 

FWIW, `shell` and `console` also don't seem to affect the copying of `$` in GitHub's UI either. 🤷

**Review by dlorenc — APPROVED** [review]

**Comment by elfotografo007** [comment]
What about if I just remove the `$`?

**Comment by imjasonh** [comment]
> What about if I just remove the `$`?

That's just crazy enough to work! 😆

https://github.com/sigstore/sigstore-website/pull/111

**Pull request merged**
