### PR TITLE
Rename to remove standard claiming wording

### PR DESCRIPTION
**Pull request by lukehinds**

### CODE REVIEW

**Review by trevrosen — APPROVED** [review]

**Comment by trevrosen** [comment]
Another quick thought: I think we should probably not use a contraction in the sub-title with "software's", as I think it can be a bit rough on non-native English speakers. I suggest changing to the expanded "software is".

**Comment by lukehinds** [comment]
@trevrosen sorry, missed your reply, will get on that!

**Comment by trevrosen** [comment]
@lukehinds anything I can do here to push this forward? I assume since you're pushing from your fork I can't easily just commit to this branch 😄

**Comment by lukehinds** [comment]
@trevrosen : https://github.com/sigstore/sigstore-website/pull/246/commits/a2f0379586dc9c493aad1a46900ac85a4c25edbe

**Comment by trevrosen** [comment]
@lukehinds :shipit: 😸

**Review by trevrosen — APPROVED** [review]

**Comment by trevrosen** [comment]
Fixing in a new PR.

**Pull request closed without merging**
