### PR TITLE
fix: Overflow issue of container for mobile devices

### PR DESCRIPTION
**Pull request by Neilblaze**
### **Description**

The container overflow issue has been fixed for mobile devices & now it works seamlessly on most devices including Pixel, iPhone, Galaxy, etc. most of the devices.

**Resolves** #132 
cc: @kimsterv, @remram44

### **Screenshots** 👇🏼 

| Original             |  New (fixed) |
:-------------------------:|:-------------------------:
image  |  image

### CODE REVIEW

**Comment by remram44** [comment]
I confirm that it's fixed for me on Firefox Android on Pixel (https://clever-cray-18c671.netlify.app/)

**Comment by Neilblaze** [comment]
@ltagliaferri Would you mind taking a look please take a look at this? 😄

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
What about having the logos break at a point onto a second line? I checked out out your PR locally, and if I minimize the screen it overflows still, and if I make it mobile-size, the logos are too small to easily read.

Firefox:

Screenshot 2023-03-27 at 4 58 49 PM

Screenshot 2023-03-27 at 5 00 19 PM

Chrome: 

Screenshot 2023-03-27 at 5 01 24 PM

Screenshot 2023-03-27 at 5 01 41 PM

**Comment by Neilblaze** [comment]
> I minimize the screen it overflows still

@ltagliaferri I'm afraid that it might break on devices having uncommon aspect ratios (like `20:9` which is for Galaxy Fold & for `17:12` which is for Google Nest Hub). But for 95% of modern devices, it should work. I've tried it out on different devices, e.g. Pixel, iPhone, and other android devices, etc. & it works seamlessly.

> What about having the logos break at a point onto a second line?

I gave it a thought, that I'll break it into 2 rows, but then stuck to the original design because of uneven positioning as there are an odd number of logos (9) & breaking those nine icons into two grids won't be symmetric cause of one extra residue. Additionally, `3x3` will be consuming too much space on the same viewport, which I kind of avoided.

**Comment by Neilblaze** [comment]
Okay lemme take one more shot then.

**Comment by Neilblaze** [comment]
@ltagliaferri is it better now? 🤔 

rec-sigstore

**Review by ltagliaferri — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
